"""Validate and emit CardDefs for explicitly reviewed textless vanilla minions."""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_card_support_analysis import collect_card_blocks, sha256, write_if_changed  # noqa: E402

DECL = ROOT / "integrations/rosettastone/card_rules/metadata_only.v1.json"
from standard_profile import load_profile, profile_path
PROFILE = load_profile()
CATALOG = profile_path(PROFILE, "catalog")
HEADER = ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets/ManaMindMetadataOnlyCardsGen.hpp"
SOURCE = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets/ManaMindMetadataOnlyCardsGen.cpp"
MANIFEST = ROOT / "integrations/rosettastone/card_rules/metadata_only.generated.json"
ALLOWLIST = {"Core_CS2_200", "TIME_053", "TLC_248"}
OTHER_MANIFESTS = (
    "core_aliases.generated.json", "effect_composition.generated.json", "after_attack_draw.generated.json",
    "repeated_trigger_draw.generated.json", "filtered_school_draw.generated.json", "keyword_only.generated.json",
)


def main() -> None:
    declaration = json.loads(DECL.read_text(encoding="utf-8"))
    if set(declaration) != {"schema_version", "catalog_path", "catalog_sha256", "cards"} or declaration["schema_version"] != 1:
        raise ValueError("unexpected metadata-only declaration schema")
    if declaration["catalog_path"] != PROFILE["catalog"] or declaration["catalog_sha256"] != sha256(CATALOG):
        raise ValueError("catalog fingerprint changed; re-review textless cards before regeneration")
    catalog = {card["id"]: card for card in json.loads(CATALOG.read_text(encoding="utf-8"))["cards"] if card.get("id")}
    own_source = SOURCE.relative_to(ROOT).as_posix()
    blocks = {card_id: block for card_id, block in collect_card_blocks().items()
              if block["source_file"] != own_source}
    owners: set[str] = set()
    for filename in OTHER_MANIFESTS:
        path = ROOT / "integrations/rosettastone/card_rules" / filename
        if path.exists():
            owners.update(row.get("card_id") for row in json.loads(path.read_text(encoding="utf-8")).get("cards", [])
                          if isinstance(row, dict))
    rows, seen = [], set()
    for item in declaration["cards"]:
        if set(item) != {"card_id"}:
            raise ValueError(f"unexpected declaration fields: {item}")
        card_id = item["card_id"]
        if card_id not in ALLOWLIST or card_id in seen:
            raise ValueError(f"card is duplicate or not allowlisted: {card_id}")
        if card_id in blocks or card_id in owners:
            raise ValueError(f"CardDef already owned by another route: {card_id}")
        seen.add(card_id)
        card = catalog.get(card_id)
        if not card or card.get("collectible") is not True or card.get("type") != "MINION":
            raise ValueError(f"not a collectible minion: {card_id}")
        if card.get("text", "").strip() or card.get("mechanics", []):
            raise ValueError(f"card is not textless and mechanic-free: {card_id}")
        stats = {key: card.get(key) for key in ("cost", "attack", "health")}
        if any(type(value) is not int or value < 0 for value in stats.values()):
            raise ValueError(f"invalid printed stats: {card_id}")
        rows.append({"card_id": card_id, "name": card["name"], "stats": stats,
                     "races": card.get("races", []),
                     "metadata_record_sha256": hashlib.sha256(json.dumps(card, ensure_ascii=False,
                         sort_keys=True, separators=(",", ":")).encode()).hexdigest(),
                     "training_eligible": False})
    if seen != ALLOWLIST:
        raise ValueError(f"declaration must include all allowlisted cards: missing {sorted(ALLOWLIST - seen)}")

    header = '''// Generated by scripts/generate_metadata_only_cards.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_METADATA_ONLY_CARDS_GEN_HPP
#define ROSETTASTONE_MANAMIND_METADATA_ONLY_CARDS_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode { class ManaMindMetadataOnlyCardsGen { public: static void AddAll(std::map<std::string, CardDef>& cards); }; }
#endif
'''
    source = ["// Generated by scripts/generate_metadata_only_cards.py. Do not edit by hand.",
              "#include <Rosetta/PlayMode/CardSets/ManaMindMetadataOnlyCardsGen.hpp>", "#include <stdexcept>",
              "namespace RosettaStone::PlayMode {", "void ManaMindMetadataOnlyCardsGen::AddAll(std::map<std::string, CardDef>& cards) {"]
    for row in rows:
        card_id = row["card_id"]
        variable = "cardDef_" + re.sub(r"\W", "_", card_id)
        source += [f'    if (cards.contains("{card_id}")) throw std::logic_error("duplicate generated CardDef: {card_id}");',
                   f"    CardDef {variable};", f"    {variable}.ClearData();", f"    {variable}.power.AddPowerTask(nullptr);",
                   f'    cards.emplace("{card_id}", {variable});']
    source += ["}", "}  // namespace RosettaStone::PlayMode", ""]
    manifest = {"schema_version": 1, "declaration": DECL.relative_to(ROOT).as_posix(),
                "declaration_sha256": sha256(DECL), "catalog_sha256": sha256(CATALOG),
                "generated_header": HEADER.relative_to(ROOT).as_posix(),
                "generated_source": SOURCE.relative_to(ROOT).as_posix(), "cards": rows,
                "training_eligible": False,
                "training_blockers": ["Textless metadata is not independent rules evidence.",
                                      "Full dependency, bridge action and match gates remain outstanding."]}
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, "\n".join(source))
    write_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Generated {len(rows)} metadata-only CardDefs; training remains disabled.")


if __name__ == "__main__":
    main()
