"""Generate reviewed minion-set consumers without consumer-specific behavior."""
from __future__ import annotations

import hashlib
import json
import re

from build_card_support_analysis import sha256, write_if_changed
from card_rules.minion_set_enchant import (
    IDENTIFIER, fields, require, render_tasks, target_requirements, validate_effects,
)
from standard_profile import ROOT, load_profile, profile_path

RULES = ROOT / "integrations/rosettastone/card_rules"
DECLARATION = RULES / "minion_set_enchant.v1.json"
MANIFEST = RULES / "minion_set_enchant.generated.json"
HEADER = ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets/ManaMindMinionSetEnchantGen.hpp"
SOURCE = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets/ManaMindMinionSetEnchantGen.cpp"


def record_hash(row: dict) -> str:
    return hashlib.sha256(json.dumps(row, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode()).hexdigest()


def validate(document: dict, catalog: dict, resources: dict) -> list[dict]:
    fields(document, {"schema_version", "package_id", "contract_id", "contract_version",
                      "implementation_kind", "reviewed_card_ids", "dependencies", "cards"})
    require(all(type(document[k]) is int and document[k] == 1 for k in ("schema_version", "contract_version")),
            "unsupported schema/contract version")
    require(document["package_id"] == "minion_set_enchant_v1" and document["contract_id"] == "minion_set_enchant",
            "contract identity mismatch")
    require(document["implementation_kind"] == "REUSABLE_CAPABILITY", "implementation kind mismatch")
    deps = document["dependencies"]
    require(isinstance(deps, dict) and bool(deps), "reviewed dependencies required")
    for ref, dependency in deps.items():
        require(bool(IDENTIFIER.fullmatch(ref)), "invalid dependency ID")
        fields(dependency, {"contract", "attack_delta", "health_delta", "metadata_sha256", "source_owner", "owner_sha256"})
        require(dependency["contract"] == "FIXED_STATS_ENCHANT_V1", "unreviewed dependency contract")
        require(all(type(dependency[k]) is int and 0 <= dependency[k] <= 100 for k in ("attack_delta", "health_delta")), "invalid fixed stats")
        meta = resources.get(ref)
        require(meta is not None and meta.get("type") == "ENCHANTMENT", "missing enchantment metadata")
        require(record_hash(meta) == dependency["metadata_sha256"], "stale dependency metadata")
        owner = (ROOT / dependency["source_owner"]).resolve()
        require(owner.is_relative_to(ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets"), "invalid owner path")
        require(owner.exists() and sha256(owner) == dependency["owner_sha256"], "stale/missing dependency owner")
        require(len(re.findall(rf'cards\.emplace\(\s*"{re.escape(ref)}"', owner.read_text(encoding="utf-8"))) == 1,
                "dependency owner must register exactly once")
    allowlist = document["reviewed_card_ids"]
    require(isinstance(allowlist, list) and all(isinstance(cid, str) for cid in allowlist), "invalid review allowlist")
    require(len(allowlist) == len(set(allowlist)), "duplicate review ID")
    rows = document["cards"]
    require(isinstance(rows, list) and bool(rows), "cards required")
    seen = set()
    for row in rows:
        fields(row, {"card_id", "metadata_sha256", "activation", "effects"})
        cid = row["card_id"]
        require(isinstance(cid, str) and bool(IDENTIFIER.fullmatch(cid)), "invalid card ID")
        require(cid in allowlist and cid not in seen, "unreviewed/duplicate consumer")
        seen.add(cid)
        meta = catalog.get(cid)
        require(meta is not None and meta.get("collectible") is True, "missing collectible metadata")
        require(record_hash(meta) == row["metadata_sha256"], "stale consumer metadata")
        require(meta.get("type") == ("SPELL" if row["activation"] == "SPELL" else "MINION"), "activation/type mismatch")
        require(row["activation"] != "BATTLECRY" or "BATTLECRY" in meta.get("mechanics", []), "Battlecry metadata required")
        validate_effects(row["activation"], row["effects"], deps)
    require(seen == set(allowlist), "declarations must exactly match reviewed membership")
    for path in (ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets").glob("*.cpp"):
        if path == SOURCE:
            continue
        text = path.read_text(encoding="utf-8")
        for cid in seen:
            require(not re.search(rf'cards\.emplace\(\s*"{re.escape(cid)}"', text), "consumer already has an owner")
    return sorted(rows, key=lambda row: row["card_id"])


def generate(rows: list[dict]) -> tuple[str, str]:
    header = '''// Generated by scripts/generate_minion_set_enchant.py. Do not edit.
#pragma once
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode {
class ManaMindMinionSetEnchantGen {
 public: static void AddAll(std::map<std::string, CardDef>& cards);
};
}
'''
    blocks = []
    for row in rows:
        cid = row["card_id"]
        lines = [f'    if (cards.contains("{cid}")) throw std::logic_error("duplicate generated CardDef: {cid}");',
                 "    {", "        CardDef cardDef;", "        cardDef.ClearData();"]
        for req in target_requirements(row["effects"]):
            lines.append(f"        cardDef.property.playReqs.emplace(PlayReq::REQ_{req}, 0);")
        activation = "AddPowerTask"  # MINION BATTLECRY activation is owned by native metadata.
        for task in render_tasks(row["effects"]):
            lines.append(f"        cardDef.power.{activation}({task});")
        lines += [f'        cards.emplace("{cid}", std::move(cardDef));', "    }"]
        blocks.append("\n".join(lines))
    source = '''// Generated by scripts/generate_minion_set_enchant.py. Do not edit.
#include <Rosetta/PlayMode/CardSets/ManaMindMinionSetEnchantGen.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/IncludeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FilterStackTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SetGameTagTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode {
void ManaMindMinionSetEnchantGen::AddAll(std::map<std::string, CardDef>& cards) {
    using namespace SimpleTasks;
''' + "\n\n".join(blocks) + "\n}\n}\n"
    return header, source


def main() -> None:
    profile = load_profile()
    catalog_path = profile_path(profile, "catalog")
    catalog = {c["id"]: c for c in json.loads(catalog_path.read_text(encoding="utf-8"))["cards"]}
    resources = {c["id"]: c for c in json.loads((ROOT / "vendor/RosettaStone/Resources/cards.json").read_text(encoding="utf-8"))}
    declaration = json.loads(DECLARATION.read_text(encoding="utf-8"))
    rows = validate(declaration, catalog, resources)
    header, source = generate(rows)
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, source)
    manifest = {k: declaration[k] for k in ("schema_version", "package_id", "contract_id", "contract_version", "implementation_kind", "dependencies")}
    manifest.update({"declaration": DECLARATION.relative_to(ROOT).as_posix(), "declaration_sha256": sha256(DECLARATION),
                     "expected_semantics_sha256": sha256(ROOT / "docs/proposals/minion_set_enchant_v1_expected_semantics.md"),
                     "catalog_sha256": sha256(catalog_path), "renderer_sha256": sha256(ROOT / "scripts/card_rules/minion_set_enchant.py"),
                     "generated_header": HEADER.relative_to(ROOT).as_posix(), "generated_source": SOURCE.relative_to(ROOT).as_posix(),
                     "cards": [{**r, "rules_text_sha256": record_hash(catalog[r["card_id"]].get("text", "")),
                                "dependencies": sorted({e["enchantment_ref"] for e in r["effects"] if "enchantment_ref" in e}),
                                "task_types": sorted({re.search(r"make_shared<([^>]+)>", t)[1] for t in render_tasks(r["effects"])}),
                                "implementation_kind": "REUSABLE_CAPABILITY", "training_eligible": False} for r in rows],
                     "training_eligible": False})
    write_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Generated {len(rows)} declaration-only minion-set consumers.")


if __name__ == "__main__":
    main()
