"""Generate profile-reviewed deck minion cost-threshold consumers."""
from __future__ import annotations

import hashlib
import json
import re

from build_card_support_analysis import sha256, write_if_changed
from card_rules.profile_deck_minion_cost_summon import (
    render_tasks,
    require,
    validate_activation,
    validate_selection,
)
from card_rules.minion_set_enchant import fields
from standard_profile import ROOT, load_profile, profile_path

RULES = ROOT / "integrations/rosettastone/card_rules"
DECLARATION = RULES / "profile_deck_minion_cost_summon.v1.json"
MANIFEST = RULES / "profile_deck_minion_cost_summon.generated.json"
HEADER = ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets/ManaMindProfileDeckMinionCostSummonGen.hpp"
SOURCE = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets/ManaMindProfileDeckMinionCostSummonGen.cpp"
OWNER_ROOT = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets"


def record_hash(row: dict) -> str:
    return hashlib.sha256(
        json.dumps(row, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode()
    ).hexdigest()


def validate(document: dict, catalog: dict, resources: dict, meta_profile: dict) -> list[dict]:
    fields(document, {"schema_version", "package_id", "contract_id", "contract_version",
                      "implementation_kind", "reviewed_card_ids", "dependencies", "cards"})
    require(document["schema_version"] == document["contract_version"] == 1,
            "unsupported schema/contract version")
    require(document["package_id"] == "profile_deck_minion_cost_threshold_v1" and
            document["contract_id"] == "deck_minion_cost_threshold_summon",
            "contract identity mismatch")
    require(document["implementation_kind"] == "REUSABLE_CAPABILITY",
            "implementation kind mismatch")
    rows = document["cards"]
    allowlist = document["reviewed_card_ids"]
    require(isinstance(rows, list) and len(rows) >= 2, "two or more reviewed consumers prove reuse")
    require(isinstance(allowlist, list) and len(allowlist) == len(set(allowlist)),
            "invalid review allowlist")
    require(set(allowlist) == {slot.get("card_id") for deck in meta_profile["decks"]
                              for slot in deck["slots"]} & set(allowlist),
            "every reviewed consumer must be a canonical profile root")

    dependencies = document["dependencies"]
    fields(dependencies, {"ULD_178a4"})
    rush = dependencies["ULD_178a4"]
    fields(rush, {"contract", "metadata_sha256", "source_owner", "owner_sha256"})
    require(rush["contract"] == "RUSH_KEYWORD_ENCHANT_V1", "unreviewed Rush enchant contract")
    require(rush["metadata_sha256"] == record_hash(resources.get("ULD_178a4", {})),
            "stale/missing Rush enchant metadata")
    owner = (ROOT / rush["source_owner"]).resolve()
    require(owner.is_relative_to(OWNER_ROOT) and owner.exists(), "invalid Rush enchant owner")
    require(sha256(owner) == rush["owner_sha256"], "stale Rush enchant source owner")
    owner_text = owner.read_text(encoding="utf-8")
    require(len(re.findall(r'cards\.emplace\(\s*"ULD_178a4"', owner_text)) == 1 and
            bool(re.search(r'AddEnchant\(std::make_unique<Enchant>\(Effects::Rush\)\)', owner_text)),
            "Rush enchant behavior is not owned by the reviewed source block")

    seen = set()
    for row in sorted(rows, key=lambda item: item["card_id"]):
        fields(row, {"card_id", "metadata_sha256", "activation", "selection", "grant_rush"})
        card_id = row["card_id"]
        require(isinstance(card_id, str) and card_id in allowlist and card_id not in seen,
                "unreviewed/duplicate consumer")
        seen.add(card_id)
        meta = catalog.get(card_id)
        require(meta is not None and meta.get("collectible") is True, "missing collectible metadata")
        require(row["metadata_sha256"] == record_hash(meta), "stale consumer metadata")
        validate_activation(row["activation"])
        validate_selection(row["selection"])
        require(type(row["grant_rush"]) is bool, "grant_rush must be boolean")
        if row["activation"]["type"] == "BATTLECRY":
            require(meta.get("type") == "MINION" and "BATTLECRY" in meta.get("mechanics", []),
                    "Battlecry consumer metadata mismatch")
        else:
            require(meta.get("type") == "SPELL", "TURN_END consumer must be a spell")
    require(seen == set(allowlist), "declarations must exactly match reviewed membership")
    for path in OWNER_ROOT.glob("*.cpp"):
        if path == SOURCE:
            continue
        text = path.read_text(encoding="utf-8")
        for card_id in seen:
            require(not re.search(rf'cards\.emplace\(\s*"{re.escape(card_id)}"', text),
                    f"consumer already has an owner: {card_id}")
    return sorted(rows, key=lambda row: row["card_id"])


def generate(rows: list[dict]) -> tuple[str, str]:
    header = '''// Generated by scripts/generate_profile_deck_minion_cost_summon.py. Do not edit.
#pragma once
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode {
class ManaMindProfileDeckMinionCostSummonGen {
 public: static void AddAll(std::map<std::string, CardDef>& cards);
};
}
'''
    blocks = []
    for row in sorted(rows, key=lambda item: item["card_id"]):
        card_id = row["card_id"]
        lines = [
            f'    if (cards.contains("{card_id}")) throw std::logic_error("duplicate generated CardDef: {card_id}");',
            "    {",
            "        CardDef cardDef;",
            "        cardDef.ClearData();",
        ]
        tasks = render_tasks(row, "ULD_178a4")
        if row["activation"]["type"] == "BATTLECRY":
            lines.extend(f"        cardDef.power.AddPowerTask({task});" for task in tasks)
        else:
            trigger_count = row["activation"]["trigger_limit"]
            lines.extend([
                "        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));",
                "        cardDef.power.GetTrigger()->tasks = {",
                *[f"            {task}," for task in tasks],
                "        };",
                f"        cardDef.power.GetTrigger()->lastTurn = {trigger_count};",
            ])
        lines += [f'        cards.emplace("{card_id}", std::move(cardDef));', "    }"]
        blocks.append("\n".join(lines))
    source = '''// Generated by scripts/generate_profile_deck_minion_cost_summon.py. Do not edit.
#include <Rosetta/PlayMode/CardSets/ManaMindProfileDeckMinionCostSummonGen.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/IncludeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FilterStackTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/RandomTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SummonStackTask.hpp>
#include <Rosetta/PlayMode/Triggers/Trigger.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
#include <vector>
namespace RosettaStone::PlayMode {
void ManaMindProfileDeckMinionCostSummonGen::AddAll(std::map<std::string, CardDef>& cards) {
    using namespace SimpleTasks;
''' + "\n\n".join(blocks) + "\n}\n}\n"
    return header, source


def main() -> None:
    profile = load_profile()
    catalog_path = profile_path(profile, "catalog")
    catalog = {c["id"]: c for c in json.loads(catalog_path.read_text(encoding="utf-8"))["cards"]}
    resources = {c["id"]: c for c in json.loads(
        (ROOT / "vendor/RosettaStone/Resources/cards.json").read_text(encoding="utf-8")
    )}
    meta_profile = json.loads((ROOT / "configs/training_profiles/meta_training_20261002_v1.json").read_text(encoding="utf-8"))
    declaration = json.loads(DECLARATION.read_text(encoding="utf-8"))
    rows = validate(declaration, catalog, resources, meta_profile)
    header, source = generate(rows)
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, source)
    manifest = {
        key: declaration[key] for key in (
            "schema_version", "package_id", "contract_id", "contract_version",
            "implementation_kind", "reviewed_card_ids", "dependencies",
        )
    }
    manifest.update({
        "declaration": DECLARATION.relative_to(ROOT).as_posix(),
        "declaration_sha256": sha256(DECLARATION),
        "renderer_sha256": sha256(ROOT / "scripts/card_rules/profile_deck_minion_cost_summon.py"),
        "catalog_sha256": sha256(catalog_path),
        "generated_header": HEADER.relative_to(ROOT).as_posix(),
        "generated_source": SOURCE.relative_to(ROOT).as_posix(),
        "cards": [
            {
                **row,
                "rules_text_sha256": record_hash(catalog[row["card_id"]].get("text", "")),
                "implementation_kind": "REUSABLE_CAPABILITY",
                "dependency_ids": ["ULD_178a4"] if row["grant_rush"] else [],
                "training_eligible": False,
            }
            for row in rows
        ],
        "training_eligible": False,
    })
    write_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Generated {len(rows)} declaration-only deck-minion consumers.")


if __name__ == "__main__":
    main()
