"""Validate a narrow Deathrattle spell-school draw package and emit C++."""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_card_support_analysis import sha256, write_if_changed  # noqa: E402

DECLARATION = ROOT / "integrations/rosettastone/card_rules/filtered_school_draw.v1.json"
from standard_profile import load_profile, profile_path
PROFILE = load_profile()
CATALOG = profile_path(PROFILE, "catalog")
HEADER = ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets/ManaMindFilteredSchoolDrawGen.hpp"
SOURCE = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets/ManaMindFilteredSchoolDrawGen.cpp"
MANIFEST = ROOT / "integrations/rosettastone/card_rules/filtered_school_draw.generated.json"
EXPECTED = {
    "FIR_929": ("Deathrattle: Draw a Fire spell.", "FIRE"),
    "RLK_511": ("Deathrattle: Draw a Frost spell.", "FROST"),
}
ALLOWED_SCHOOLS = {"FIRE", "FROST"}


def normalized(text: str) -> str:
    text = re.sub(r"\[x\]", "", text or "", flags=re.I)
    return " ".join(re.sub(r"<[^>]+>", "", text).lower().split())


def require(ok: bool, message: str) -> None:
    if not ok:
        raise ValueError(message)


def validate() -> tuple[list[dict], str]:
    catalog_hash = sha256(CATALOG)
    declaration = json.loads(DECLARATION.read_text(encoding="utf-8"))
    require(set(declaration) == {"schema_version", "catalog_path", "catalog_sha256", "cards"},
            "unknown or missing root fields")
    require(declaration["schema_version"] == 1, "unsupported schema_version")
    require(declaration["catalog_path"] == CATALOG.relative_to(ROOT).as_posix(), "catalog path mismatch")
    require(declaration["catalog_sha256"] in ("", catalog_hash), "catalog fingerprint is stale")
    catalog = {card["id"]: card for card in json.loads(CATALOG.read_text(encoding="utf-8"))["cards"]}
    require(len(declaration["cards"]) == len(EXPECTED), "package card count changed")
    seen: set[str] = set()
    validated = []
    for row in declaration["cards"]:
        require(set(row) == {"card_id", "spell_school", "amount"}, "unknown or missing card fields")
        card_id = row["card_id"]
        require(card_id in EXPECTED and card_id not in seen, f"unreviewed or duplicate card: {card_id}")
        seen.add(card_id)
        card = catalog.get(card_id)
        require(card is not None and card.get("collectible") is True, f"missing collectible card: {card_id}")
        expected_text, expected_school = EXPECTED[card_id]
        require(normalized(card.get("text", "")) == normalized(expected_text), f"rules text changed: {card_id}")
        require(row["spell_school"] == expected_school and row["spell_school"] in ALLOWED_SCHOOLS,
                f"unreviewed spell school: {card_id}")
        require(type(row["amount"]) is int and row["amount"] == 1, f"unreviewed draw count: {card_id}")
        require(card.get("type") == "MINION", f"Deathrattle source is not a minion: {card_id}")
        validated.append({
            "card_id": card_id,
            "name": card["name"],
            "trigger": "DEATHRATTLE",
            "spell_school": row["spell_school"],
            "amount": row["amount"],
            "rules_text_sha256": hashlib.sha256(normalized(card["text"]).encode()).hexdigest(),
            "training_eligible": False,
        })
    require(seen == set(EXPECTED), "declaration does not exactly match the allowlist")

    roots = [(ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets", "*.cpp"),
             (ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets", "*.hpp")]
    for root, pattern in roots:
        for path in root.rglob(pattern):
            if path == SOURCE:
                continue
            source = path.read_text(encoding="utf-8", errors="ignore")
            for card_id in EXPECTED:
                require(not re.search(rf'cards\.emplace\("{card_id}"', source),
                        f"existing CardDef found for {card_id} in {path.relative_to(ROOT)}")
    return validated, catalog_hash


def generate(cards: list[dict]) -> tuple[str, str]:
    header = '''// Generated by scripts/generate_filtered_school_draw.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
#define ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode
{
class ManaMindFilteredSchoolDrawGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode
#endif  // ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
'''
    blocks = []
    for card in cards:
        cid = card["card_id"]
        school = card["spell_school"]
        block = [f'    if (cards.contains("{cid}"))',
                 f'        throw std::logic_error("duplicate generated CardDef: {cid}");',
                 '    {', '        CardDef cardDef;', '        cardDef.ClearData();',
                 f'        cardDef.power.AddDeathrattleTask(std::make_shared<DrawSpellTask>(SpellSchool::{school}, {card["amount"]}));',
                 f'        cards.emplace("{cid}", std::move(cardDef));', '    }']
        blocks.append("\n".join(block))
    source = '''// Generated by scripts/generate_filtered_school_draw.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindFilteredSchoolDrawGen.hpp>
#include <Rosetta/PlayMode/Cards/CardPowers.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawSpellTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode
{
void ManaMindFilteredSchoolDrawGen::AddAll(std::map<std::string, CardDef>& cards)
{
using namespace SimpleTasks;

'''+"\n\n".join(blocks)+'''
}
}  // namespace RosettaStone::PlayMode
'''
    return header, source


def main() -> None:
    cards, catalog_hash = validate()
    header, source = generate(cards)
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, source)
    declaration = json.loads(DECLARATION.read_text(encoding="utf-8"))
    declaration["catalog_sha256"] = catalog_hash
    write_if_changed(DECLARATION, json.dumps(declaration, ensure_ascii=False, indent=2) + "\n")
    manifest = {
        "schema_version": 1,
        "declaration": DECLARATION.relative_to(ROOT).as_posix(),
        "declaration_sha256": sha256(DECLARATION),
        "catalog_sha256": catalog_hash,
        "generated_header": HEADER.relative_to(ROOT).as_posix(),
        "generated_source": SOURCE.relative_to(ROOT).as_posix(),
        "cards": cards,
        "training_eligible": False,
        "training_blockers": ["Deck membership and full Standard rules/action gates remain unresolved."],
    }
    write_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Validated and generated {len(cards)} filtered-school draw cards (catalog {catalog_hash[:12]}).")


if __name__ == "__main__":
    main()
