"""Generate ordinary CardDefs from strict declarations and reviewed CUSTOM emitters."""
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
from build_card_support_analysis import sha256, write_if_changed
from card_rules.composition_validation import validate, DECLARATION, HEADER, SOURCE, MANIFEST
from card_rules.composition_ops import implementation_route
from card_rules.custom_emitters import generated_source

def main():
    cards, catalog_hash = validate()
    for card in cards:
        card["implementation_route"] = implementation_route(card)
    header = '''// Generated by scripts/generate_effect_composition.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
#define ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode
{
class ManaMindEffectCompositionGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode
#endif  // ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
'''
    manifest = {"schema_version": 1, "declaration": DECLARATION.relative_to(ROOT).as_posix(),
                "declaration_sha256": sha256(DECLARATION), "catalog_sha256": catalog_hash,
                "generated_header": HEADER.relative_to(ROOT).as_posix(), "generated_source": SOURCE.relative_to(ROOT).as_posix(),
                "cards": cards, "training_eligible": False,
                "training_blockers": ["This package is a migration pilot, not a deck-complete proof.",
                                      "Generated card scenarios and deck dependency gates remain outstanding."]}
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, generated_source(cards))
    write_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Generated {len(cards)} effect compositions; training remains disabled.")


if __name__ == "__main__":
    main()
