"""Validate and emit CardDefs for cards whose complete text is supported keywords."""
from __future__ import annotations
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_card_support_analysis import norm_text, write_if_changed  # noqa: E402

DECL = ROOT / "integrations/rosettastone/card_rules/keyword_only.v1.json"
from standard_profile import load_profile, profile_path
PROFILE = load_profile()
CATALOG = profile_path(PROFILE, "catalog")
HEADER = ROOT / "vendor/RosettaStone/Includes/Rosetta/PlayMode/CardSets/ManaMindKeywordOnlyCardsGen.hpp"
SOURCE = ROOT / "vendor/RosettaStone/Sources/Rosetta/PlayMode/CardSets/ManaMindKeywordOnlyCardsGen.cpp"
MANIFEST = ROOT / "integrations/rosettastone/card_rules/keyword_only.generated.json"
LABEL_TO_MECHANIC = {"lifesteal": "LIFESTEAL", "reborn": "REBORN", "rush": "RUSH",
                     "stealth": "STEALTH", "spell damage +1": "SPELLPOWER",
                     "taunt": "TAUNT", "overload": "OVERLOAD"}

def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def main() -> None:
    d = json.loads(DECL.read_text(encoding="utf-8"))
    if set(d) != {"schema_version", "catalog_path", "catalog_sha256", "cards"} or d["schema_version"] != 1:
        raise ValueError("unexpected declaration schema")
    if d["catalog_path"] != PROFILE["catalog"] or d["catalog_sha256"] != sha(CATALOG):
        raise ValueError("catalog fingerprint changed; review declarations before regeneration")
    cards = {c["id"]: c for c in json.loads(CATALOG.read_text(encoding="utf-8"))["cards"] if c.get("id")}
    owned_elsewhere = set()
    for filename in ("core_aliases.generated.json", "effect_composition.generated.json",
                     "after_attack_draw.generated.json", "repeated_trigger_draw.generated.json",
                     "filtered_school_draw.generated.json", "metadata_only.generated.json"):
        path = ROOT / "integrations/rosettastone/card_rules" / filename
        if path.exists():
            owned_elsewhere.update(row.get("card_id") for row in json.loads(path.read_text(encoding="utf-8")).get("cards", []))
    rows, seen = [], set()
    for item in d["cards"]:
        if set(item) != {"card_id", "mechanics"} or item["card_id"] in seen:
            raise ValueError(f"invalid or duplicate declaration: {item}")
        if item["card_id"] in owned_elsewhere:
            raise ValueError(f"card already owned by another generated route: {item['card_id']}")
        seen.add(item["card_id"])
        c = cards.get(item["card_id"])
        if not c or c.get("type") not in {"MINION", "WEAPON"}:
            raise ValueError(f"missing or unsupported card type: {item['card_id']}")
        declared = set(item["mechanics"])
        if not declared or declared != set(c.get("mechanics", [])):
            raise ValueError(f"mechanics mismatch: {item['card_id']}")
        text = c.get("text", "")
        labels = re.findall(r"<b>([^<]+)</b>", text, flags=re.I)
        remainder = re.sub(r"<b>[^<]+</b>", "", text, flags=re.I)
        remainder = re.sub(r"</?[^>]+>", "", remainder)
        mapped = {LABEL_TO_MECHANIC.get(label.strip().lower()) for label in labels}
        normalized_remainder = norm_text(remainder).strip(" ,.;:")
        if "OVERLOAD" in declared:
            expected_overload = c.get("overload")
            if not isinstance(expected_overload, int) or normalized_remainder != str(expected_overload):
                raise ValueError(f"Overload amount does not match pinned metadata: {item['card_id']}")
            normalized_remainder = ""
        if not labels or normalized_remainder or None in mapped or mapped != declared:
            raise ValueError(f"rules text is not exactly the allowlisted keyword set: {item['card_id']}")
        rows.append({"card_id": item["card_id"], "name": c["name"], "mechanics": sorted(declared),
                     "rules_text_sha256": hashlib.sha256(norm_text(text).encode()).hexdigest(), "training_eligible": False})
    header = """// Generated by scripts/generate_keyword_only_cards.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_KEYWORD_ONLY_CARDS_GEN_HPP
#define ROSETTASTONE_MANAMIND_KEYWORD_ONLY_CARDS_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode { class ManaMindKeywordOnlyCardsGen { public: static void AddAll(std::map<std::string, CardDef>& cards); }; }
#endif
"""
    source = ["// Generated by scripts/generate_keyword_only_cards.py. Do not edit by hand.",
              "#include <Rosetta/PlayMode/CardSets/ManaMindKeywordOnlyCardsGen.hpp>", "#include <stdexcept>",
              "namespace RosettaStone::PlayMode {", "void ManaMindKeywordOnlyCardsGen::AddAll(std::map<std::string, CardDef>& cards) {"]
    for row in rows:
        cid = row["card_id"]
        source += [f'    if (cards.contains("{cid}")) throw std::logic_error("duplicate generated CardDef: {cid}");',
                   f"    CardDef cardDef_{cid};", f"    cardDef_{cid}.ClearData();", f"    cardDef_{cid}.power.AddPowerTask(nullptr);",
                   f'    cards.emplace("{cid}", cardDef_{cid});']
    source += ["}", "}  // namespace RosettaStone::PlayMode", ""]
    manifest = {"schema_version": 1, "declaration": "integrations/rosettastone/card_rules/keyword_only.v1.json",
                "declaration_sha256": sha(DECL), "catalog_sha256": sha(CATALOG),
                "generated_header": HEADER.relative_to(ROOT).as_posix(), "generated_source": SOURCE.relative_to(ROOT).as_posix(), "cards": rows}
    write_if_changed(HEADER, header)
    write_if_changed(SOURCE, "\n".join(source))
    write_if_changed(MANIFEST, json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    print(f"Generated {len(rows)} keyword-only CardDefs")

if __name__ == "__main__":
    main()
